apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
        - name: redis-client
          image: redis-client:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: redis-client-service
spec:
  selector:
    app: redis-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: redis-client.example.com
      http:
        paths:
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: redis-client-service
                port:
                  number: 80
