apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: ZGJ1c2Vy  # dbuser
  password: c2VjdXJlcGFzcw==  # securepass

---
apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
stringData:
  apiKey: "my-super-secret-api-key"

---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
type: Opaque
stringData:
  ssh-privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAt5...
    -----END RSA PRIVATE KEY-----

---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
stringData:
  smtp-user: "mailer@example.com"
  smtp-password: "smtpsecure123"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
type: Opaque
data:
  redis-password: cmVkaXNwYXNz  # redispass

---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account
type: Opaque
stringData:
  service-account.json: |
    {
      "type": "service_account",
      "project_id": "my-project",
      ...
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-key
type: Opaque
data:
  key: MTIzNDU2Nzg5MDEyMzQ1Ng==  # 1234567890123456
